/**
 * Headcount Narration — Fallback Templates
 * 
 * Used when the LLM is unavailable or repeatedly fails the numeric guard.
 * Only uses safe string interpolation of exact evidence data.
 */

import type { VerdictObject } from '@engine/types';

export function getFallbackNarration(verdictObj: VerdictObject): string {
  const {
    verdict,
    effective_holders,
    analysed_holders,
    total_addresses,
    independence_ratio,
    supply_coverage,
    signals
  } = verdictObj;

  const pct = (val: number) => (val * 100).toFixed(1) + '%';
  const ratio = (val: number) => (val * 100).toFixed(1) + '%';

  const intro = `Claims ${total_addresses.toLocaleString()} holders. Analysed: top ${analysed_holders} by balance (${pct(supply_coverage)} of supply). Effective holders: ${effective_holders}. Independence ratio: ${independence_ratio.toFixed(3)}.`;
  
  const hhiDelta = (signals.cluster_adjusted_hhi - signals.naive_hhi).toFixed(3);
  
  switch (verdict) {
    case 'ORGANIC':
      return `${intro} The distribution shows high independence (${ratio(independence_ratio)}) and active external use (${ratio(signals.exogenous_rate)}), indicative of organic retail distribution.`;
      
    case 'MANUFACTURED':
      if (independence_ratio < 0.40) {
        return `${intro} The distribution is heavily clustered (independence ratio ${ratio(independence_ratio)}), indicating a manufactured holder count generated by a small number of operators funding multiple wallets.`;
      }
      return `${intro} The distribution exhibits highly coordinated acquisition patterns (birth dispersion ${ratio(signals.birth_dispersion)}) and low external utility (${ratio(signals.exogenous_rate)}), characteristic of a manufactured holder count.`;
      
    case 'CONCENTRATED':
      if (parseFloat(hhiDelta) > 0.15) {
        return `${intro} While independence is moderate, cluster merging reveals significant hidden concentration (HHI delta +${hhiDelta}), meaning supply is tightly controlled by a few operators.`;
      }
      return `${intro} The distribution shows moderate independence (${ratio(independence_ratio)}) but falls short of organic thresholds. Supply is concentrated among a smaller number of independent operators than the raw holder count suggests.`;
      
    case 'UNVERIFIABLE':
      return `Analysis unverifiable. We were unable to resolve funding origins for a sufficient portion of the holder base, or the circulating supply is too thinly distributed among the top ${analysed_holders} holders (${pct(supply_coverage)}).`;
  }
}
